USE SchoolSystemDB;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Courses' AND COLUMN_NAME = 'Name')
BEGIN
	ALTER TABLE Courses
	ADD Name NVARCHAR(255) NOT NULL DEFAULT '';
END

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = 'Courses' AND COLUMN_NAME = 'Active')
BEGIN
	ALTER TABLE Courses
	ADD Active BIT NOT NULL DEFAULT 1;
END
GO